/*
 * The MIT License
 *
 * Copyright 2017 ADRIAN.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package advpkmnteamplanner;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author ADRIAN
 */
public class MainForm extends javax.swing.JFrame {

    AdvPkmnTeamPlanner mainClass = new AdvPkmnTeamPlanner();
    List<JComboBox> type1Grp = new ArrayList<JComboBox>();
    List<JComboBox> type2Grp = new ArrayList<JComboBox>();

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();

        type1Grp.add(p1t1ComboBox);
        type1Grp.add(p2t1ComboBox);
        type1Grp.add(p3t1ComboBox);
        type1Grp.add(p4t1ComboBox);
        type1Grp.add(p5t1ComboBox);
        type1Grp.add(p6t1ComboBox);

        type2Grp.add(p1t2ComboBox);
        type2Grp.add(p2t2ComboBox);
        type2Grp.add(p3t2ComboBox);
        type2Grp.add(p4t2ComboBox);
        type2Grp.add(p5t2ComboBox);
        type2Grp.add(p6t2ComboBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputPanel = new javax.swing.JPanel();
        p1t1ComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        p1t2ComboBox = new javax.swing.JComboBox<>();
        p2t1ComboBox = new javax.swing.JComboBox<>();
        p2t2ComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p3t1ComboBox = new javax.swing.JComboBox<>();
        p3t2ComboBox = new javax.swing.JComboBox<>();
        p4t2ComboBox = new javax.swing.JComboBox<>();
        p4t1ComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        p5t1ComboBox = new javax.swing.JComboBox<>();
        p5t2ComboBox = new javax.swing.JComboBox<>();
        p6t2ComboBox = new javax.swing.JComboBox<>();
        p6t1ComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        clearBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        weaknessTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Advance Pkmn Team Planner");

        inputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Pkmn"));

        p1t1ComboBox.setModel(new DefaultComboBoxModel(Data.TYPE_LIST.toArray()));
        p1t1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWeaknessTable(evt);
            }
        });

        jLabel1.setText("Type 1: ");

        jLabel2.setText("Type 2:");

        jLabel3.setText("Pkmn #1");
        jLabel3.setToolTipText("");

        p1t2ComboBox.setModel(new DefaultComboBoxModel(Data.TYPE_LIST.toArray()));
        p1t2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWeaknessTable(evt);
            }
        });

        p2t1ComboBox.setModel(new DefaultComboBoxModel(Data.TYPE_LIST.toArray()));
        p2t1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWeaknessTable(evt);
            }
        });

        p2t2ComboBox.setModel(new DefaultComboBoxModel(Data.TYPE_LIST.toArray()));
        p2t2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWeaknessTable(evt);
            }
        });

        jLabel4.setText("Pkmn #2");
        jLabel4.setToolTipText("");

        jLabel5.setText("Pkmn #3");
        jLabel5.setToolTipText("");

        p3t1ComboBox.setModel(new DefaultComboBoxModel(Data.TYPE_LIST.toArray()));
        p3t1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWeaknessTable(evt);
            }
        });

        p3t2ComboBox.setModel(new DefaultComboBoxModel(Data.TYPE_LIST.toArray()));
        p3t2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWeaknessTable(evt);
            }
        });

        p4t2ComboBox.setModel(new DefaultComboBoxModel(Data.TYPE_LIST.toArray()));
        p4t2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWeaknessTable(evt);
            }
        });

        p4t1ComboBox.setModel(new DefaultComboBoxModel(Data.TYPE_LIST.toArray()));
        p4t1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWeaknessTable(evt);
            }
        });

        jLabel6.setText("Pkmn #4");
        jLabel6.setToolTipText("");

        jLabel7.setText("Pkmn #5");
        jLabel7.setToolTipText("");

        p5t1ComboBox.setModel(new DefaultComboBoxModel(Data.TYPE_LIST.toArray()));
        p5t1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWeaknessTable(evt);
            }
        });

        p5t2ComboBox.setModel(new DefaultComboBoxModel(Data.TYPE_LIST.toArray()));
        p5t2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWeaknessTable(evt);
            }
        });

        p6t2ComboBox.setModel(new DefaultComboBoxModel(Data.TYPE_LIST.toArray()));
        p6t2ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWeaknessTable(evt);
            }
        });

        p6t1ComboBox.setModel(new DefaultComboBoxModel(Data.TYPE_LIST.toArray()));
        p6t1ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateWeaknessTable(evt);
            }
        });

        jLabel8.setText("Pkmn #6");
        jLabel8.setToolTipText("");

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p6t2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(inputPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(p1t1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(inputPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(p1t2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel3)))
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(p2t1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p2t2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p3t1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p3t2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel5)))
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p4t2ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p4t1ComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p5t1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p5t2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel7)))
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(p6t1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel8)))))
                .addGap(18, 18, 18)
                .addComponent(clearBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p2t1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p1t1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p3t1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p4t1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p5t1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p6t1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p2t2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p1t2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p3t2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p4t2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p5t2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(p6t2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(clearBtn))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        weaknessTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Normal", null, null, null, null, null, null, null, null, null, null, "Normal"},
                {"Fight", null, null, null, null, null, null, null, null, null, null, "Fight"},
                {"Flying", null, null, null, null, null, null, null, null, null, null, "Flying"},
                {"Poison", null, null, null, null, null, null, null, null, null, null, "Poison"},
                {"Ground", null, null, null, null, null, null, null, null, null, null, "Ground"},
                {"Rock", null, null, null, null, null, null, null, null, null, null, "Rock"},
                {"Bug", null, null, null, null, null, null, null, null, null, null, "Bug"},
                {"Ghost", null, null, null, null, null, null, null, null, null, null, "Ghost"},
                {"Steel", null, null, null, null, null, null, null, null, null, null, "Steel"},
                {"Fire", null, null, null, null, null, null, null, null, null, null, "Fire"},
                {"Wafer", null, null, null, null, null, null, null, null, null, null, "Water"},
                {"Grass", null, null, null, null, null, null, null, null, null, null, "Grass"},
                {"Electric", null, null, null, null, null, null, null, null, null, null, "Electric"},
                {"Psyhic", null, null, null, null, null, null, null, null, null, null, "Psyhic"},
                {"Ice", null, null, null, null, null, null, null, null, null, null, "Ice"},
                {"Dragon", null, null, null, null, null, null, null, null, null, null, "Dragon"},
                {"Dark", null, null, null, null, null, null, null, null, null, null, "Dark"},
                {"Fairy", null, null, null, null, null, null, null, null, null, null, "Fairy"}
            },
            new String [] {
                "", "Pkmn 1", "Pkmn 2", "Pkmn 3 ", "Pkmn 4", "Pkmn 5", "Pkmn 6", "", "Resist", "Immune", "Weak", ""
            }
        ));
        weaknessTable.setEnabled(false);
        jScrollPane2.setViewportView(weaknessTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        for (Component c : inputPanel.getComponents()) {
            if (c.getClass().toString().contains("JComboBox")) {
                JComboBox combo = (JComboBox) c;
                combo.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_clearBtnActionPerformed

    private void updateWeaknessTable(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateWeaknessTable
       
        for (int i = 0; i < Data.TYPE_LIST.size() - 1; i++) {
            double totalWeakness = 0;
            int resistCount=0;
            int immuneCount =0;
            int weakCount =0;
            
            for (int j = 0; j < Data.MAX_PKMN; j++) {
                JComboBox comboBox1 =type1Grp.get(j);
                JComboBox comboBox2= type2Grp.get(j);
                String type1 = comboBox1.getSelectedItem().toString();
                String type2 = comboBox2.getSelectedItem().toString();
                
                

                if (type1.equals(Data.NONE_TEXT) && type2.equals(Data.NONE_TEXT)) {
                    weaknessTable.getModel().setValueAt("", i, j + 1);
                } else {
                    if (type1.equalsIgnoreCase(type2)) {
                        comboBox2.setSelectedIndex(0);
                        type2 = Data.NONE_TEXT;
                    }
                    double weakness1;
                    if (type1.equals(Data.NONE_TEXT)) {
                        weakness1 = 1;
                    } else {
                        weakness1 = mainClass.getWeaknessMultiplier(i, Data.ConvertTypeStringToInt(type1));
                    }

                    double weakness2;
                    if (type2.equals(Data.NONE_TEXT)) {
                        weakness2 = 1;
                    } else {
                        weakness2 = mainClass.getWeaknessMultiplier(i, Data.ConvertTypeStringToInt(type2));
                    }
                    totalWeakness = weakness1 * weakness2;
                    if(totalWeakness == 0){
                        immuneCount++;
                        //to change cell color
                    } else if(totalWeakness > 1){
                        weakCount++;
                    } else if(totalWeakness > 0 && totalWeakness < 1) {
                        resistCount++;
                    }
                    weaknessTable.getModel().setValueAt(totalWeakness, i, j + 1);
                }
                
                weaknessTable.getModel().setValueAt(resistCount, i, 8);
                weaknessTable.getModel().setValueAt(immuneCount, i, 9);
                weaknessTable.getModel().setValueAt(weakCount, i, 10);
            }
        }
    }//GEN-LAST:event_updateWeaknessTable


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> p1t1ComboBox;
    private javax.swing.JComboBox<String> p1t2ComboBox;
    private javax.swing.JComboBox<String> p2t1ComboBox;
    private javax.swing.JComboBox<String> p2t2ComboBox;
    private javax.swing.JComboBox<String> p3t1ComboBox;
    private javax.swing.JComboBox<String> p3t2ComboBox;
    private javax.swing.JComboBox<String> p4t1ComboBox;
    private javax.swing.JComboBox<String> p4t2ComboBox;
    private javax.swing.JComboBox<String> p5t1ComboBox;
    private javax.swing.JComboBox<String> p5t2ComboBox;
    private javax.swing.JComboBox<String> p6t1ComboBox;
    private javax.swing.JComboBox<String> p6t2ComboBox;
    private javax.swing.JTable weaknessTable;
    // End of variables declaration//GEN-END:variables
}
